# Generated by Django 5.1.4 on 2025-01-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=200)),
                ('date_depart', models.IntegerField()),
                ('heure_depart', models.IntegerField()),
                ('departure_station', models.SmallIntegerField(null=True)),
                ('arrival_station', models.SmallIntegerField(null=True)),
                ('seat_occupation_flag', models.SmallIntegerField(null=True)),
            ],
        ),
    ]
