# Generated by Django 5.1.4 on 2025-01-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeatManagementAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='arrival_station',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='seat',
            name='departure_station',
            field=models.CharField(max_length=20),
        ),
    ]
